package RTT.corba;


/**
* RTT/corba/CArgumentDescription.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OperationInterface.idl
* Wednesday, July 11, 2012 5:26:50 PM CEST
*/

public final class CArgumentDescription implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;

  //! Argument name
  public String description = null;

  //! Argument description
  public String type = null;

  public CArgumentDescription ()
  {
  } // ctor

  public CArgumentDescription (String _name, String _description, String _type)
  {
    name = _name;
    description = _description;
    type = _type;
  } // ctor

} // class CArgumentDescription
