package RTT.corba;

/**
* RTT/corba/CArgumentDescriptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OperationInterface.idl
* Wednesday, July 11, 2012 5:26:49 PM CEST
*/

public final class CArgumentDescriptionHolder implements org.omg.CORBA.portable.Streamable
{
  public RTT.corba.CArgumentDescription value = null;

  public CArgumentDescriptionHolder ()
  {
  }

  public CArgumentDescriptionHolder (RTT.corba.CArgumentDescription initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTT.corba.CArgumentDescriptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTT.corba.CArgumentDescriptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTT.corba.CArgumentDescriptionHelper.type ();
  }

}
