package RTT.corba;

/**
* RTT/corba/CCallInterruptedHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OperationInterface.idl
* Wednesday, July 11, 2012 5:26:50 PM CEST
*/

public final class CCallInterruptedHolder implements org.omg.CORBA.portable.Streamable
{
  public RTT.corba.CCallInterrupted value = null;

  public CCallInterruptedHolder ()
  {
  }

  public CCallInterruptedHolder (RTT.corba.CCallInterrupted initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTT.corba.CCallInterruptedHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTT.corba.CCallInterruptedHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTT.corba.CCallInterruptedHelper.type ();
  }

}
