package RTT.corba;


/**
* RTT/corba/CChannelElementHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DataFlow.idl
* Wednesday, July 11, 2012 5:26:42 PM CEST
*/


/**
     * Represents the basic channel element interface
     * for reading, writing and disconnecting a channel.
     * Use this interface in case you want to communicate
     * with an Orocos component's port from a non-Orocos application.
     */
abstract public class CChannelElementHelper
{
  private static String  _id = "IDL:RTT/corba/CChannelElement:1.0";

  public static void insert (org.omg.CORBA.Any a, RTT.corba.CChannelElement that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static RTT.corba.CChannelElement extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (RTT.corba.CChannelElementHelper.id (), "CChannelElement");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static RTT.corba.CChannelElement read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CChannelElementStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, RTT.corba.CChannelElement value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static RTT.corba.CChannelElement narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof RTT.corba.CChannelElement)
      return (RTT.corba.CChannelElement)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      RTT.corba._CChannelElementStub stub = new RTT.corba._CChannelElementStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static RTT.corba.CChannelElement unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof RTT.corba.CChannelElement)
      return (RTT.corba.CChannelElement)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      RTT.corba._CChannelElementStub stub = new RTT.corba._CChannelElementStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
