package RTT.corba;


/**
* RTT/corba/CConnectionModel.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DataFlow.idl
* Wednesday, July 11, 2012 5:26:42 PM CEST
*/

public class CConnectionModel implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static RTT.corba.CConnectionModel[] __array = new RTT.corba.CConnectionModel [__size];

  public static final int _CData = 0;
  public static final RTT.corba.CConnectionModel CData = new RTT.corba.CConnectionModel(_CData);
  public static final int _CBuffer = 1;
  public static final RTT.corba.CConnectionModel CBuffer = new RTT.corba.CConnectionModel(_CBuffer);

  public int value ()
  {
    return __value;
  }

  public static RTT.corba.CConnectionModel from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected CConnectionModel (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class CConnectionModel
