package RTT.corba;

/**
* RTT/corba/CConfigurationInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ConfigurationInterface.idl
* Wednesday, July 11, 2012 5:26:13 PM CEST
*/


/**
	 * Exposes both attributes and properties
	 * of a service.
	 * @ingroup CompIDL
	 */
public final class CConfigurationInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public RTT.corba.CConfigurationInterface value = null;

  public CConfigurationInterfaceHolder ()
  {
  }

  public CConfigurationInterfaceHolder (RTT.corba.CConfigurationInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTT.corba.CConfigurationInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTT.corba.CConfigurationInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTT.corba.CConfigurationInterfaceHelper.type ();
  }

}
