package RTT.corba;

/**
* RTT/corba/CConnectionModelHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DataFlow.idl
* Wednesday, July 11, 2012 5:26:42 PM CEST
*/

public final class CConnectionModelHolder implements org.omg.CORBA.portable.Streamable
{
  public RTT.corba.CConnectionModel value = null;

  public CConnectionModelHolder ()
  {
  }

  public CConnectionModelHolder (RTT.corba.CConnectionModel initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTT.corba.CConnectionModelHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTT.corba.CConnectionModelHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTT.corba.CConnectionModelHelper.type ();
  }

}
