package RTT.corba;


/**
* RTT/corba/CConnPolicyHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DataFlow.idl
* Wednesday, July 11, 2012 5:26:42 PM CEST
*/

abstract public class CConnPolicyHelper
{
  private static String  _id = "IDL:RTT/corba/CConnPolicy:1.0";

  public static void insert (org.omg.CORBA.Any a, RTT.corba.CConnPolicy that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static RTT.corba.CConnPolicy extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [8];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = RTT.corba.CConnectionModelHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "type",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[1] = new org.omg.CORBA.StructMember (
            "init",
            _tcOf_members0,
            null);
          _tcOf_members0 = RTT.corba.CLockPolicyHelper.type ();
          _members0[2] = new org.omg.CORBA.StructMember (
            "lock_policy",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[3] = new org.omg.CORBA.StructMember (
            "pull",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[4] = new org.omg.CORBA.StructMember (
            "size",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[5] = new org.omg.CORBA.StructMember (
            "transport",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[6] = new org.omg.CORBA.StructMember (
            "data_size",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[7] = new org.omg.CORBA.StructMember (
            "name_id",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (RTT.corba.CConnPolicyHelper.id (), "CConnPolicy", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static RTT.corba.CConnPolicy read (org.omg.CORBA.portable.InputStream istream)
  {
    RTT.corba.CConnPolicy value = new RTT.corba.CConnPolicy ();
    value.type = RTT.corba.CConnectionModelHelper.read (istream);
    value.init = istream.read_boolean ();
    value.lock_policy = RTT.corba.CLockPolicyHelper.read (istream);
    value.pull = istream.read_boolean ();
    value.size = istream.read_long ();
    value.transport = istream.read_long ();
    value.data_size = istream.read_long ();
    value.name_id = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, RTT.corba.CConnPolicy value)
  {
    RTT.corba.CConnectionModelHelper.write (ostream, value.type);
    ostream.write_boolean (value.init);
    RTT.corba.CLockPolicyHelper.write (ostream, value.lock_policy);
    ostream.write_boolean (value.pull);
    ostream.write_long (value.size);
    ostream.write_long (value.transport);
    ostream.write_long (value.data_size);
    ostream.write_string (value.name_id);
  }

}
