package RTT.corba;

/**
* RTT/corba/CDataFlowInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DataFlow.idl
* Wednesday, July 11, 2012 5:26:42 PM CEST
*/


/**
     * An interface to access the dataflow
     * of a CControlTask object. Data ports are exported as
     * assignable expressions (Set/Get). Buffer ports are
     * exported as buffer channels.
     * @ingroup CompIDL
     */
public final class CDataFlowInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public RTT.corba.CDataFlowInterface value = null;

  public CDataFlowInterfaceHolder ()
  {
  }

  public CDataFlowInterfaceHolder (RTT.corba.CDataFlowInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTT.corba.CDataFlowInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTT.corba.CDataFlowInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTT.corba.CDataFlowInterfaceHelper.type ();
  }

}
