package RTT.corba;


/**
* RTT/corba/CFlowStatusHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DataFlow.idl
* Wednesday, July 11, 2012 5:26:42 PM CEST
*/

abstract public class CFlowStatusHelper
{
  private static String  _id = "IDL:RTT/corba/CFlowStatus:1.0";

  public static void insert (org.omg.CORBA.Any a, RTT.corba.CFlowStatus that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static RTT.corba.CFlowStatus extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (RTT.corba.CFlowStatusHelper.id (), "CFlowStatus", new String[] { "CNoData", "COldData", "CNewData"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static RTT.corba.CFlowStatus read (org.omg.CORBA.portable.InputStream istream)
  {
    return RTT.corba.CFlowStatus.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, RTT.corba.CFlowStatus value)
  {
    ostream.write_long (value.value ());
  }

}
