package RTT.corba;


/**
* RTT/corba/CFlowStatus.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DataFlow.idl
* Wednesday, July 11, 2012 5:26:42 PM CEST
*/

public class CFlowStatus implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static RTT.corba.CFlowStatus[] __array = new RTT.corba.CFlowStatus [__size];

  public static final int _CNoData = 0;
  public static final RTT.corba.CFlowStatus CNoData = new RTT.corba.CFlowStatus(_CNoData);
  public static final int _COldData = 1;
  public static final RTT.corba.CFlowStatus COldData = new RTT.corba.CFlowStatus(_COldData);
  public static final int _CNewData = 2;
  public static final RTT.corba.CFlowStatus CNewData = new RTT.corba.CFlowStatus(_CNewData);

  public int value ()
  {
    return __value;
  }

  public static RTT.corba.CFlowStatus from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected CFlowStatus (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class CFlowStatus
