package RTT.corba;


/**
* RTT/corba/CLockPolicy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DataFlow.idl
* Wednesday, July 11, 2012 5:26:42 PM CEST
*/

public class CLockPolicy implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static RTT.corba.CLockPolicy[] __array = new RTT.corba.CLockPolicy [__size];

  public static final int _CUnsync = 0;
  public static final RTT.corba.CLockPolicy CUnsync = new RTT.corba.CLockPolicy(_CUnsync);
  public static final int _CLocked = 1;
  public static final RTT.corba.CLockPolicy CLocked = new RTT.corba.CLockPolicy(_CLocked);
  public static final int _CLockFree = 2;
  public static final RTT.corba.CLockPolicy CLockFree = new RTT.corba.CLockPolicy(_CLockFree);

  public int value ()
  {
    return __value;
  }

  public static RTT.corba.CLockPolicy from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected CLockPolicy (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class CLockPolicy
