package RTT.corba;


/**
* RTT/corba/CNoCorbaTransport.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DataFlow.idl
* Wednesday, July 11, 2012 5:26:42 PM CEST
*/

public final class CNoCorbaTransport extends org.omg.CORBA.UserException
{

  public CNoCorbaTransport ()
  {
    super(CNoCorbaTransportHelper.id());
  } // ctor


  public CNoCorbaTransport (String $reason)
  {
    super(CNoCorbaTransportHelper.id() + "  " + $reason);
  } // ctor

} // class CNoCorbaTransport
