package RTT.corba;


/**
* RTT/corba/CNoCorbaTransportHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DataFlow.idl
* Wednesday, July 11, 2012 5:26:42 PM CEST
*/

abstract public class CNoCorbaTransportHelper
{
  private static String  _id = "IDL:RTT/corba/CNoCorbaTransport:1.0";

  public static void insert (org.omg.CORBA.Any a, RTT.corba.CNoCorbaTransport that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static RTT.corba.CNoCorbaTransport extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [0];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          __typeCode = org.omg.CORBA.ORB.init ().create_exception_tc (RTT.corba.CNoCorbaTransportHelper.id (), "CNoCorbaTransport", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static RTT.corba.CNoCorbaTransport read (org.omg.CORBA.portable.InputStream istream)
  {
    RTT.corba.CNoCorbaTransport value = new RTT.corba.CNoCorbaTransport ();
    // read and discard the repository ID
    istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, RTT.corba.CNoCorbaTransport value)
  {
    // write the repository ID
    ostream.write_string (id ());
  }

}
