package RTT.corba;

/**
* RTT/corba/CNoCorbaTransportHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DataFlow.idl
* Wednesday, July 11, 2012 5:26:42 PM CEST
*/

public final class CNoCorbaTransportHolder implements org.omg.CORBA.portable.Streamable
{
  public RTT.corba.CNoCorbaTransport value = null;

  public CNoCorbaTransportHolder ()
  {
  }

  public CNoCorbaTransportHolder (RTT.corba.CNoCorbaTransport initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTT.corba.CNoCorbaTransportHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTT.corba.CNoCorbaTransportHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTT.corba.CNoCorbaTransportHelper.type ();
  }

}
