package RTT.corba;

/**
* RTT/corba/CNoSuchNameExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OperationInterface.idl
* Wednesday, July 11, 2012 5:26:50 PM CEST
*/

public final class CNoSuchNameExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public RTT.corba.CNoSuchNameException value = null;

  public CNoSuchNameExceptionHolder ()
  {
  }

  public CNoSuchNameExceptionHolder (RTT.corba.CNoSuchNameException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTT.corba.CNoSuchNameExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTT.corba.CNoSuchNameExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTT.corba.CNoSuchNameExceptionHelper.type ();
  }

}
