package RTT.corba;


/**
* RTT/corba/CNoSuchPortException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DataFlow.idl
* Wednesday, July 11, 2012 5:26:42 PM CEST
*/

public final class CNoSuchPortException extends org.omg.CORBA.UserException
{

  public CNoSuchPortException ()
  {
    super(CNoSuchPortExceptionHelper.id());
  } // ctor


  public CNoSuchPortException (String $reason)
  {
    super(CNoSuchPortExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class CNoSuchPortException
