package RTT.corba;

/**
* RTT/corba/COperationInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OperationInterface.idl
* Wednesday, July 11, 2012 5:26:50 PM CEST
*/


/**
     * Exposes the operations this service offers.
     * @ingroup CompIDL
     */
public final class COperationInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public RTT.corba.COperationInterface value = null;

  public COperationInterfaceHolder ()
  {
  }

  public COperationInterfaceHolder (RTT.corba.COperationInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTT.corba.COperationInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTT.corba.COperationInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTT.corba.COperationInterfaceHelper.type ();
  }

}
