package RTT.corba;


/**
* RTT/corba/COperationInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OperationInterface.idl
* Wednesday, July 11, 2012 5:26:50 PM CEST
*/


/**
     * Exposes the operations this service offers.
     * @ingroup CompIDL
     */
public interface COperationInterface extends COperationInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface COperationInterface
