package RTT.corba;

/**
* RTT/corba/CPortDescriptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DataFlow.idl
* Wednesday, July 11, 2012 5:26:42 PM CEST
*/

public final class CPortDescriptionHolder implements org.omg.CORBA.portable.Streamable
{
  public RTT.corba.CPortDescription value = null;

  public CPortDescriptionHolder ()
  {
  }

  public CPortDescriptionHolder (RTT.corba.CPortDescription initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTT.corba.CPortDescriptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTT.corba.CPortDescriptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTT.corba.CPortDescriptionHelper.type ();
  }

}
