package RTT.corba;

/**
* RTT/corba/CPortTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DataFlow.idl
* Wednesday, July 11, 2012 5:26:42 PM CEST
*/

public final class CPortTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public RTT.corba.CPortType value = null;

  public CPortTypeHolder ()
  {
  }

  public CPortTypeHolder (RTT.corba.CPortType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTT.corba.CPortTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTT.corba.CPortTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTT.corba.CPortTypeHelper.type ();
  }

}
