package RTT.corba;


/**
* RTT/corba/CPortType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DataFlow.idl
* Wednesday, July 11, 2012 5:26:42 PM CEST
*/

public class CPortType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static RTT.corba.CPortType[] __array = new RTT.corba.CPortType [__size];

  public static final int _CInput = 0;
  public static final RTT.corba.CPortType CInput = new RTT.corba.CPortType(_CInput);
  public static final int _COutput = 1;
  public static final RTT.corba.CPortType COutput = new RTT.corba.CPortType(_COutput);

  public int value ()
  {
    return __value;
  }

  public static RTT.corba.CPortType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected CPortType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class CPortType
