package RTT.corba;


/**
* RTT/corba/CPortTypeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DataFlow.idl
* Wednesday, July 11, 2012 5:26:42 PM CEST
*/

abstract public class CPortTypeHelper
{
  private static String  _id = "IDL:RTT/corba/CPortType:1.0";

  public static void insert (org.omg.CORBA.Any a, RTT.corba.CPortType that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static RTT.corba.CPortType extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (RTT.corba.CPortTypeHelper.id (), "CPortType", new String[] { "CInput", "COutput"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static RTT.corba.CPortType read (org.omg.CORBA.portable.InputStream istream)
  {
    return RTT.corba.CPortType.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, RTT.corba.CPortType value)
  {
    ostream.write_long (value.value ());
  }

}
