package RTT.corba;


/**
* RTT/corba/CRemoteChannelElement.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DataFlow.idl
* Wednesday, July 11, 2012 5:26:42 PM CEST
*/


/**
     * The advanced channel element interface, used by Orocos
     * to relay over-CORBA data flow connections.
     */
public interface CRemoteChannelElement extends CRemoteChannelElementOperations, RTT.corba.CChannelElement, org.omg.CORBA.portable.IDLEntity 
{
} // interface CRemoteChannelElement
