package RTT.corba;


/**
* RTT/corba/CRequestNamesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServiceRequester.idl
* Wednesday, July 11, 2012 5:27:05 PM CEST
*/

public final class CRequestNamesHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public CRequestNamesHolder ()
  {
  }

  public CRequestNamesHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTT.corba.CRequestNamesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTT.corba.CRequestNamesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTT.corba.CRequestNamesHelper.type ();
  }

}
