package RTT.corba;

/**
* RTT/corba/CSendStatusHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OperationInterface.idl
* Wednesday, July 11, 2012 5:26:50 PM CEST
*/

public final class CSendStatusHolder implements org.omg.CORBA.portable.Streamable
{
  public RTT.corba.CSendStatus value = null;

  public CSendStatusHolder ()
  {
  }

  public CSendStatusHolder (RTT.corba.CSendStatus initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTT.corba.CSendStatusHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTT.corba.CSendStatusHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTT.corba.CSendStatusHelper.type ();
  }

}
