package RTT.corba;


/**
* RTT/corba/CService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Service.idl
* Wednesday, July 11, 2012 5:27:00 PM CEST
*/


/**
	 * An Orocos Service which hosts operations, attributes and properties.
	 * @ingroup CompIDL
	 */
public interface CService extends CServiceOperations, RTT.corba.COperationInterface, RTT.corba.CConfigurationInterface, RTT.corba.CDataFlowInterface
{
} // interface CService
