package RTT.corba;


/**
* RTT/corba/CServiceRequesterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServiceRequester.idl
* Wednesday, July 11, 2012 5:27:05 PM CEST
*/


/**
	 * An Orocos Required Service.
	 * Exposes that this component requires certain services.
	 * @ingroup CompIDL
	 */
public interface CServiceRequesterOperations 
{

  /**
  	     * Return the name of this service.
  	     */
  String getRequestName ();

  /**
  	     * Get a list of all the child requests this request offers.
  	     */
  String[] getRequestNames ();

  /**
  	     * Returns the methods required by this requester.
  	     */
  String[] getOperationCallerNames ();

  /**
  	     * Get a child request this request provides.
  	     */
  RTT.corba.CServiceRequester getRequest (String name);

  /**
  	     * Has this request a child request with given name ?
  	     */
  boolean hasRequest (String name);

  /**
           * Connects the whole interface to a remote service.
           */
  boolean connectTo (RTT.corba.CService svc);

  /**
  	     * Connets a single operation caller from this interface to
  	     * one with the same name in a remote service.
  	     */
  boolean connectCallerTo (String name, RTT.corba.CService svc);

  /**
           * Returns true if all operation callers are connected to
           * the operations of a service.
           */
  boolean ready ();

  /**
  	     * Disconnects a caller.
  	     * @return false if name dit not exist.
  	     */
  boolean disconnectCaller (String name);

  /**
           * Checks if a caller is ready.
           * @return false if name dit not exist or not ready.
           */
  boolean callerReady (String name);

  /**
           * Disconnects all operation callers.
           */
  void disconnect ();
} // interface CServiceRequesterOperations
