package RTT.corba;

/**
* RTT/corba/CServiceRequesterHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServiceRequester.idl
* Wednesday, July 11, 2012 5:27:05 PM CEST
*/


/**
	 * An Orocos Required Service.
	 * Exposes that this component requires certain services.
	 * @ingroup CompIDL
	 */
public final class CServiceRequesterHolder implements org.omg.CORBA.portable.Streamable
{
  public RTT.corba.CServiceRequester value = null;

  public CServiceRequesterHolder ()
  {
  }

  public CServiceRequesterHolder (RTT.corba.CServiceRequester initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTT.corba.CServiceRequesterHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTT.corba.CServiceRequesterHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTT.corba.CServiceRequesterHelper.type ();
  }

}
