package RTT.corba;


/**
* RTT/corba/CTaskState.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TaskContext.idl
* Wednesday, July 11, 2012 5:27:10 PM CEST
*/


/**
	 * Maps 1-to-1 to RTT::base::TaskCore::TaskState.
         *
         * Exception is renamed to ExceptionState as Exception is forbidden by
         * IDL
	 * @ingroup CompIDL
	 */
public class CTaskState implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 7;
  private static RTT.corba.CTaskState[] __array = new RTT.corba.CTaskState [__size];

  public static final int _CInit = 0;
  public static final RTT.corba.CTaskState CInit = new RTT.corba.CTaskState(_CInit);
  public static final int _CPreOperational = 1;
  public static final RTT.corba.CTaskState CPreOperational = new RTT.corba.CTaskState(_CPreOperational);
  public static final int _CFatalError = 2;
  public static final RTT.corba.CTaskState CFatalError = new RTT.corba.CTaskState(_CFatalError);
  public static final int _CException = 3;
  public static final RTT.corba.CTaskState CException = new RTT.corba.CTaskState(_CException);
  public static final int _CStopped = 4;
  public static final RTT.corba.CTaskState CStopped = new RTT.corba.CTaskState(_CStopped);
  public static final int _CRunning = 5;
  public static final RTT.corba.CTaskState CRunning = new RTT.corba.CTaskState(_CRunning);
  public static final int _CRunTimeError = 6;
  public static final RTT.corba.CTaskState CRunTimeError = new RTT.corba.CTaskState(_CRunTimeError);

  public int value ()
  {
    return __value;
  }

  public static RTT.corba.CTaskState from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected CTaskState (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class CTaskState
