package RTT.corba;

/**
* RTT/corba/CTaskStateHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TaskContext.idl
* Wednesday, July 11, 2012 5:27:10 PM CEST
*/


/**
	 * Maps 1-to-1 to RTT::base::TaskCore::TaskState.
         *
         * Exception is renamed to ExceptionState as Exception is forbidden by
         * IDL
	 * @ingroup CompIDL
	 */
public final class CTaskStateHolder implements org.omg.CORBA.portable.Streamable
{
  public RTT.corba.CTaskState value = null;

  public CTaskStateHolder ()
  {
  }

  public CTaskStateHolder (RTT.corba.CTaskState initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTT.corba.CTaskStateHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTT.corba.CTaskStateHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTT.corba.CTaskStateHelper.type ();
  }

}
