package RTT.corba;


/**
* RTT/corba/CTaskStateHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TaskContext.idl
* Wednesday, July 11, 2012 5:27:10 PM CEST
*/


/**
	 * Maps 1-to-1 to RTT::base::TaskCore::TaskState.
         *
         * Exception is renamed to ExceptionState as Exception is forbidden by
         * IDL
	 * @ingroup CompIDL
	 */
abstract public class CTaskStateHelper
{
  private static String  _id = "IDL:RTT/corba/CTaskState:1.0";

  public static void insert (org.omg.CORBA.Any a, RTT.corba.CTaskState that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static RTT.corba.CTaskState extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (RTT.corba.CTaskStateHelper.id (), "CTaskState", new String[] { "CInit", "CPreOperational", "CFatalError", "CException", "CStopped", "CRunning", "CRunTimeError"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static RTT.corba.CTaskState read (org.omg.CORBA.portable.InputStream istream)
  {
    return RTT.corba.CTaskState.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, RTT.corba.CTaskState value)
  {
    ostream.write_long (value.value ());
  }

}
