package RTT.corba;

/**
* RTT/corba/CWrongArgumentExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OperationInterface.idl
* Wednesday, July 11, 2012 5:26:50 PM CEST
*/

public final class CWrongArgumentExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public RTT.corba.CWrongArgumentException value = null;

  public CWrongArgumentExceptionHolder ()
  {
  }

  public CWrongArgumentExceptionHolder (RTT.corba.CWrongArgumentException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTT.corba.CWrongArgumentExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTT.corba.CWrongArgumentExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTT.corba.CWrongArgumentExceptionHelper.type ();
  }

}
