package RTT.corba;

/**
* RTT/corba/CWrongTypeArgExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OperationInterface.idl
* Wednesday, July 11, 2012 5:26:50 PM CEST
*/

public final class CWrongTypeArgExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public RTT.corba.CWrongTypeArgException value = null;

  public CWrongTypeArgExceptionHolder ()
  {
  }

  public CWrongTypeArgExceptionHolder (RTT.corba.CWrongTypeArgException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTT.corba.CWrongTypeArgExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTT.corba.CWrongTypeArgExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTT.corba.CWrongTypeArgExceptionHelper.type ();
  }

}
