package RTT.corba;


/**
* RTT/corba/CWrongNumbArgException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OperationInterface.idl
* Wednesday, July 11, 2012 5:26:50 PM CEST
*/

public final class CWrongNumbArgException extends org.omg.CORBA.UserException
{
  public int wanted = (int)0;
  public int received = (int)0;

  public CWrongNumbArgException ()
  {
    super(CWrongNumbArgExceptionHelper.id());
  } // ctor

  public CWrongNumbArgException (int _wanted, int _received)
  {
    super(CWrongNumbArgExceptionHelper.id());
    wanted = _wanted;
    received = _received;
  } // ctor


  public CWrongNumbArgException (String $reason, int _wanted, int _received)
  {
    super(CWrongNumbArgExceptionHelper.id() + "  " + $reason);
    wanted = _wanted;
    received = _received;
  } // ctor

} // class CWrongNumbArgException
