package RTT.corba;

/**
* RTT/corba/CWrongNumbArgExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OperationInterface.idl
* Wednesday, July 11, 2012 5:26:50 PM CEST
*/

public final class CWrongNumbArgExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public RTT.corba.CWrongNumbArgException value = null;

  public CWrongNumbArgExceptionHolder ()
  {
  }

  public CWrongNumbArgExceptionHolder (RTT.corba.CWrongNumbArgException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTT.corba.CWrongNumbArgExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTT.corba.CWrongNumbArgExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTT.corba.CWrongNumbArgExceptionHelper.type ();
  }

}
