package RTT.corba;


/**
* RTT/corba/CWrongTypeArgExceptionHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OperationInterface.idl
* Wednesday, July 11, 2012 5:26:50 PM CEST
*/

abstract public class CWrongTypeArgExceptionHelper
{
  private static String  _id = "IDL:RTT/corba/CWrongTypeArgException:1.0";

  public static void insert (org.omg.CORBA.Any a, RTT.corba.CWrongTypeArgException that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static RTT.corba.CWrongTypeArgException extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "whicharg",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "expected",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "received",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_exception_tc (RTT.corba.CWrongTypeArgExceptionHelper.id (), "CWrongTypeArgException", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static RTT.corba.CWrongTypeArgException read (org.omg.CORBA.portable.InputStream istream)
  {
    RTT.corba.CWrongTypeArgException value = new RTT.corba.CWrongTypeArgException ();
    // read and discard the repository ID
    istream.read_string ();
    value.whicharg = istream.read_long ();
    value.expected = istream.read_string ();
    value.received = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, RTT.corba.CWrongTypeArgException value)
  {
    // write the repository ID
    ostream.write_string (id ());
    ostream.write_long (value.whicharg);
    ostream.write_string (value.expected);
    ostream.write_string (value.received);
  }

}
