package RTT.corba;


/**
* RTT/corba/PairHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OrocosTypes.idl
* Wednesday, July 11, 2012 5:26:55 PM CEST
*/

abstract public class PairHelper
{
  private static String  _id = "IDL:RTT/corba/Pair:1.0";

  public static void insert (org.omg.CORBA.Any a, RTT.corba.Pair that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static RTT.corba.Pair extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_any);
          _members0[0] = new org.omg.CORBA.StructMember (
            "t1",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_any);
          _members0[1] = new org.omg.CORBA.StructMember (
            "t2",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (RTT.corba.PairHelper.id (), "Pair", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static RTT.corba.Pair read (org.omg.CORBA.portable.InputStream istream)
  {
    RTT.corba.Pair value = new RTT.corba.Pair ();
    value.t1 = istream.read_any ();
    value.t2 = istream.read_any ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, RTT.corba.Pair value)
  {
    ostream.write_any (value.t1);
    ostream.write_any (value.t2);
  }

}
