package RTT.corba;


/**
* RTT/corba/Pair.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OrocosTypes.idl
* Wednesday, July 11, 2012 5:26:55 PM CEST
*/

public final class Pair implements org.omg.CORBA.portable.IDLEntity
{
  public org.omg.CORBA.Any t1 = null;
  public org.omg.CORBA.Any t2 = null;

  public Pair ()
  {
  } // ctor

  public Pair (org.omg.CORBA.Any _t1, org.omg.CORBA.Any _t2)
  {
    t1 = _t1;
    t2 = _t2;
  } // ctor

} // class Pair
