package RTT.corba;

/**
* RTT/corba/PairHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OrocosTypes.idl
* Wednesday, July 11, 2012 5:26:55 PM CEST
*/

public final class PairHolder implements org.omg.CORBA.portable.Streamable
{
  public RTT.corba.Pair value = null;

  public PairHolder ()
  {
  }

  public PairHolder (RTT.corba.Pair initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTT.corba.PairHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTT.corba.PairHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTT.corba.PairHelper.type ();
  }

}
