package orogen.JOrocos.Corba;


/**
* orogen/JOrocos/Corba/Path.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../OrocosComponents/DataFlowComplexTypesTestTypesPlugin/transports/corba/DataFlowComplexTypesTestTypesPluginTypes.idl
* Friday, July 13, 2012 12:54:15 PM CEST
*/

public final class Path implements org.omg.CORBA.portable.IDLEntity
{
  public double stamp = (double)0;
  public String frameId = null;
  public orogen.JOrocos.Corba.Pose poses[] = null;

  public Path ()
  {
  } // ctor

  public Path (double _stamp, String _frameId, orogen.JOrocos.Corba.Pose[] _poses)
  {
    stamp = _stamp;
    frameId = _frameId;
    poses = _poses;
  } // ctor

} // class Path
