package orogen.JOrocos.Corba;

/**
* orogen/JOrocos/Corba/PoseHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../OrocosComponents/DataFlowComplexTypesTestTypesPlugin/transports/corba/DataFlowComplexTypesTestTypesPluginTypes.idl
* Friday, July 13, 2012 12:54:15 PM CEST
*/

public final class PoseHolder implements org.omg.CORBA.portable.Streamable
{
  public orogen.JOrocos.Corba.Pose value = null;

  public PoseHolder ()
  {
  }

  public PoseHolder (orogen.JOrocos.Corba.Pose initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = orogen.JOrocos.Corba.PoseHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    orogen.JOrocos.Corba.PoseHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return orogen.JOrocos.Corba.PoseHelper.type ();
  }

}
