package orogen.JOrocos.Corba;


/**
* orogen/JOrocos/Corba/PoseHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../OrocosComponents/DataFlowComplexTypesTestTypesPlugin/transports/corba/DataFlowComplexTypesTestTypesPluginTypes.idl
* Friday, July 13, 2012 12:54:15 PM CEST
*/

abstract public class PoseHelper
{
  private static String  _id = "IDL:orogen/JOrocos/Corba/Pose:1.0";

  public static void insert (org.omg.CORBA.Any a, orogen.JOrocos.Corba.Pose that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static orogen.JOrocos.Corba.Pose extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = orogen.JOrocos.Corba.Vector3Helper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "position",
            _tcOf_members0,
            null);
          _tcOf_members0 = orogen.JOrocos.Corba.QuaternionHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "orientation",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (orogen.JOrocos.Corba.PoseHelper.id (), "Pose", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static orogen.JOrocos.Corba.Pose read (org.omg.CORBA.portable.InputStream istream)
  {
    orogen.JOrocos.Corba.Pose value = new orogen.JOrocos.Corba.Pose ();
    value.position = orogen.JOrocos.Corba.Vector3Helper.read (istream);
    value.orientation = orogen.JOrocos.Corba.QuaternionHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, orogen.JOrocos.Corba.Pose value)
  {
    orogen.JOrocos.Corba.Vector3Helper.write (ostream, value.position);
    orogen.JOrocos.Corba.QuaternionHelper.write (ostream, value.orientation);
  }

}
