package orogen.JOrocos.Corba;

/**
* orogen/JOrocos/Corba/QuaternionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../OrocosComponents/DataFlowComplexTypesTestTypesPlugin/transports/corba/DataFlowComplexTypesTestTypesPluginTypes.idl
* Friday, July 13, 2012 12:54:15 PM CEST
*/

public final class QuaternionHolder implements org.omg.CORBA.portable.Streamable
{
  public orogen.JOrocos.Corba.Quaternion value = null;

  public QuaternionHolder ()
  {
  }

  public QuaternionHolder (orogen.JOrocos.Corba.Quaternion initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = orogen.JOrocos.Corba.QuaternionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    orogen.JOrocos.Corba.QuaternionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return orogen.JOrocos.Corba.QuaternionHelper.type ();
  }

}
