package orogen.JOrocos.Corba;


/**
* orogen/JOrocos/Corba/Quaternion.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../OrocosComponents/DataFlowComplexTypesTestTypesPlugin/transports/corba/DataFlowComplexTypesTestTypesPluginTypes.idl
* Friday, July 13, 2012 12:54:15 PM CEST
*/

public final class Quaternion implements org.omg.CORBA.portable.IDLEntity
{
  public double x = (double)0;
  public double y = (double)0;
  public double z = (double)0;
  public double w = (double)0;

  public Quaternion ()
  {
  } // ctor

  public Quaternion (double _x, double _y, double _z, double _w)
  {
    x = _x;
    y = _y;
    z = _z;
    w = _w;
  } // ctor

} // class Quaternion
