package orogen.JOrocos.Corba;


/**
* orogen/JOrocos/Corba/Vector3.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../OrocosComponents/DataFlowComplexTypesTestTypesPlugin/transports/corba/DataFlowComplexTypesTestTypesPluginTypes.idl
* Friday, July 13, 2012 12:54:15 PM CEST
*/

public final class Vector3 implements org.omg.CORBA.portable.IDLEntity
{
  public double x = (double)0;
  public double y = (double)0;
  public double z = (double)0;

  public Vector3 ()
  {
  } // ctor

  public Vector3 (double _x, double _y, double _z)
  {
    x = _x;
    y = _y;
    z = _z;
  } // ctor

} // class Vector3
