package orogen.JOrocos.Corba;


/**
* orogen/JOrocos/Corba/vector__JOrocos_Pose_Holder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../OrocosComponents/DataFlowComplexTypesTestTypesPlugin/transports/corba/DataFlowComplexTypesTestTypesPluginTypes.idl
* Friday, July 13, 2012 12:54:15 PM CEST
*/

public final class vector__JOrocos_Pose_Holder implements org.omg.CORBA.portable.Streamable
{
  public orogen.JOrocos.Corba.Pose value[] = null;

  public vector__JOrocos_Pose_Holder ()
  {
  }

  public vector__JOrocos_Pose_Holder (orogen.JOrocos.Corba.Pose[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = orogen.JOrocos.Corba.vector__JOrocos_Pose_Helper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    orogen.JOrocos.Corba.vector__JOrocos_Pose_Helper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return orogen.JOrocos.Corba.vector__JOrocos_Pose_Helper.type ();
  }

}
