package orogen.JOrocos.Corba;

/**
* orogen/JOrocos/Corba/Vector3Holder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../OrocosComponents/DataFlowComplexTypesTestTypesPlugin/transports/corba/DataFlowComplexTypesTestTypesPluginTypes.idl
* Friday, July 13, 2012 12:54:15 PM CEST
*/

public final class Vector3Holder implements org.omg.CORBA.portable.Streamable
{
  public orogen.JOrocos.Corba.Vector3 value = null;

  public Vector3Holder ()
  {
  }

  public Vector3Holder (orogen.JOrocos.Corba.Vector3 initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = orogen.JOrocos.Corba.Vector3Helper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    orogen.JOrocos.Corba.Vector3Helper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return orogen.JOrocos.Corba.Vector3Helper.type ();
  }

}
