package RTT.corba.CServicePackage;


/**
* RTT/corba/CServicePackage/CProviderNamesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Service.idl
* Wednesday, July 11, 2012 5:27:00 PM CEST
*/

public final class CProviderNamesHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public CProviderNamesHolder ()
  {
  }

  public CProviderNamesHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTT.corba.CServicePackage.CProviderNamesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTT.corba.CServicePackage.CProviderNamesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTT.corba.CServicePackage.CProviderNamesHelper.type ();
  }

}
