package RTT.corba.CConfigurationInterfacePackage;


/**
* RTT/corba/CConfigurationInterfacePackage/CAttributeNamesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ConfigurationInterface.idl
* Wednesday, July 11, 2012 5:26:13 PM CEST
*/

public final class CAttributeNamesHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public CAttributeNamesHolder ()
  {
  }

  public CAttributeNamesHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTT.corba.CConfigurationInterfacePackage.CAttributeNamesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTT.corba.CConfigurationInterfacePackage.CAttributeNamesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTT.corba.CConfigurationInterfacePackage.CAttributeNamesHelper.type ();
  }

}
