package RTT.corba.CConfigurationInterfacePackage;


/**
* RTT/corba/CConfigurationInterfacePackage/CProperty.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ConfigurationInterface.idl
* Wednesday, July 11, 2012 5:26:13 PM CEST
*/

public final class CProperty implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String description = null;

  public CProperty ()
  {
  } // ctor

  public CProperty (String _name, String _description)
  {
    name = _name;
    description = _description;
  } // ctor

} // class CProperty
