package RTT.corba.CConfigurationInterfacePackage;

/**
* RTT/corba/CConfigurationInterfacePackage/CPropertyHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ConfigurationInterface.idl
* Wednesday, July 11, 2012 5:26:13 PM CEST
*/

public final class CPropertyHolder implements org.omg.CORBA.portable.Streamable
{
  public RTT.corba.CConfigurationInterfacePackage.CProperty value = null;

  public CPropertyHolder ()
  {
  }

  public CPropertyHolder (RTT.corba.CConfigurationInterfacePackage.CProperty initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTT.corba.CConfigurationInterfacePackage.CPropertyHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTT.corba.CConfigurationInterfacePackage.CPropertyHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTT.corba.CConfigurationInterfacePackage.CPropertyHelper.type ();
  }

}
