package RTT.corba.CDataFlowInterfacePackage;


/**
* RTT/corba/CDataFlowInterfacePackage/CPortNamesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DataFlow.idl
* Wednesday, July 11, 2012 5:26:42 PM CEST
*/

public final class CPortNamesHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public CPortNamesHolder ()
  {
  }

  public CPortNamesHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTT.corba.CDataFlowInterfacePackage.CPortNamesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTT.corba.CDataFlowInterfacePackage.CPortNamesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTT.corba.CDataFlowInterfacePackage.CPortNamesHelper.type ();
  }

}
