package RTT.corba.CDataFlowInterfacePackage;


/**
* RTT/corba/CDataFlowInterfacePackage/CPortDescriptionsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DataFlow.idl
* Wednesday, July 11, 2012 5:26:42 PM CEST
*/

public final class CPortDescriptionsHolder implements org.omg.CORBA.portable.Streamable
{
  public RTT.corba.CPortDescription value[] = null;

  public CPortDescriptionsHolder ()
  {
  }

  public CPortDescriptionsHolder (RTT.corba.CPortDescription[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTT.corba.CDataFlowInterfacePackage.CPortDescriptionsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTT.corba.CDataFlowInterfacePackage.CPortDescriptionsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTT.corba.CDataFlowInterfacePackage.CPortDescriptionsHelper.type ();
  }

}
