package RTT.corba.CTaskContextPackage;


/**
* RTT/corba/CTaskContextPackage/CPeerNamesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TaskContext.idl
* Wednesday, July 11, 2012 5:27:10 PM CEST
*/

public final class CPeerNamesHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public CPeerNamesHolder ()
  {
  }

  public CPeerNamesHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RTT.corba.CTaskContextPackage.CPeerNamesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RTT.corba.CTaskContextPackage.CPeerNamesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RTT.corba.CTaskContextPackage.CPeerNamesHelper.type ();
  }

}
